input{
    tcp {
        port => 5044
        codec => json
        tags => ["backend"]
    }
    http {
        port => 5045
        codec => json
        tags => ["frontend"]
    }
}

filter {
    if "backend" in [tags] {
        mutate { add_field => { "source" => "backend" } }
    }
    if "frontend" in [tags] {
        mutate { add_field => { "source" => "frontend" } }
    }
    mutate {
        add_field => { "received_at" => "%{@timestamp}" }
    }
}

output {
    elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "logstash_logs-%{+YYYY.MM.dd}" 
    }
    stdout { codec => rubydebug }
}